name: 'Setup Kubernetes Tools'
description: 'Setup Kubernetes tools: kubectl, kustomize, helm, kubeconform, conftest, yq, rancher, tilt, skaffold, kube-score'
author: 'Yoichi Kawasaki @yokawasa'
inputs:
  fail-fast:
    required: false
    default: 'true'
    description: 'the action immediately fails when it fails to download (ie. due to a bad version)'
  arch-type:
    required: false
    default: 'amd64'
    description: 'The processor architecture type of the tool binary to setup. Supported types are only "amd64" and "arm64". If a type other than the supported Types is specified, it will be treated as "amd64"'
  setup-tools:
    required: false
    default: ''
    description: 'List of tool name to setup. By default, the action download and setup all supported Kubernetes tools. By specifying "setup-tools" you can choose which tools the action setup. Supported separator is return in multi-line string. Supported tools are "kubectl", "kustomize", "helm", "helmv3", "kubeval", "conftest", "yq", "rancher", "tilt", "skaffold", "kube-score"'
  kubectl:
    required: false
    default: '1.24.10'
    description: 'kubectl version'
  kustomize:
    required: false
    default: '5.0.0'
    description: 'kustomize version'
  helm:
    required: false
    default: '3.11.1'
    description: 'helm version'
  kubeval:
    required: false
    default: '0.16.1'
    description: 'kubeval version'
  kubeconform:
    required: false
    default: '0.5.0'
    description: 'kubeconform version'
  conftest:
    required: false
    default: '0.39.0'
    description: 'conftest version'
  yq:
    required: false
    default: '4.30.7'
    description: 'yq version'
  rancher:
    required: false
    default: '2.7.0'
    description: 'rancher cli version'
  tilt:
    required: false
    default: '0.31.2'
    description: 'tilt version'
  skaffold:
    required: false
    default: '2.1.0'
    description: 'skaffold version'
  kube-score:
    required: false
    default: '1.16.1'
    description: 'kube-score version'
outputs:
  kubectl-path:
    description: 'kubectl command path if the action setup the tool, otherwise empty string'
  kustomize-path:
    description: 'kustomize command path if the action setup the tool, otherwise empty string'
  helm-path:
    description: 'helm command path if the action setup the tool, otherwise empty string'
  kubeval-path:
    description: 'kubeval command path if the action setup the tool, otherwise empty string'
  conftest-path:
    description: 'conftest command path if the action setup the tool, otherwise empty string'
  yq-path:
    description: 'yq command path if the action setup the tool, otherwise empty string'
  rancher-path:
    description: 'rancher cli command path if the action setup the tool, otherwise empty string'
  tilt-path:
    description: 'tilt command path if the action setup the tool, otherwise empty string'
  skaffold-path:
    description: 'skaffold command path if the action setup the tool, otherwise empty string'
  kube-score-path:
    description: 'kube-score command path if the action setup the tool, otherwise empty string'
branding:
  icon: 'terminal'
  color: 'blue'
runs:
  using: 'node20'
  main: 'dist/index.js'
