export const defaultProcessorArchType = 'amd64'

export const defaultKubectlVersion = '1.35.3'
export const defaultKustomizeVersion = '5.8.1'
export const defaultHelmVersion = '3.20.1'
export const defaultKubevalVersion = '0.16.1'
export const defaultKubeconformVersion = '0.7.0'
export const defaultConftestVersion = '0.67.1'
export const defaultYqVersion = '4.52.5'
export const defaultRancherVersion = '2.13.3'
export const defaultTiltVersion = '0.37.0'
export const defaultSkaffoldVersion = '2.18.1'
export const defaultKubeScoreVersion = '1.20.0'
